version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uwsgi docker/api/uwsgi.ini
    restart: always
    ports:
     - "8001:8001"
  trt-nginx:
    image: nginx:1.17.9
    restart: always
    environment:
      TZ: Europe/Moscow
    volumes:
     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params:ro
    depends_on:
     - trt-uwsgi
    ports:
     - "80:80"
