#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cat << EOF > ${SCRIPT_DIR}/openstack.env
OS_AUTH_URL=${OS_AUTH_URL}
OS_IDENTITY_API_VERSION=${OS_IDENTITY_API_VERSION}
OS_VOLUME_API_VERSION=${OS_VOLUME_API_VERSION}
CLIFF_FIT_WIDTH=${CLIFF_FIT_WIDTH}
OS_PROJECT_DOMAIN_NAME=${OS_PROJECT_DOMAIN_NAME}
OS_PROJECT_ID=${OS_PROJECT_ID}
OS_TENANT_ID=${OS_TENANT_ID}
OS_REGION_NAME=${OS_REGION_NAME}
OS_USER_DOMAIN_NAME=${OS_USER_DOMAIN_NAME}
OS_USERNAME=${OS_USERNAME}
OS_PASSWORD=${OS_PASSWORD}
EOF